Акишкина Вероника
urfu-2018/markup-task-3 pull request #102
Opened 2018-10-23 12:17 UTC by AirenLaird

Газетка

2018-10-23 12:18 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 12:27 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 12:46 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 12:50 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 12:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 13:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 13:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 09:20 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 09:32 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 09:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 10:26 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 10:31 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 10:52 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 11:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 21:11 UTC, SemyonMakhaev requested changes
🍅 

Привет! Получилось красиво)

А как же вертикальный текст?
А цитаты в тексте? Для них нужно использовать семантичный тег.

Старайся избегать селекторов по тегу. Селекторы класса позволят сделать твою вёрстку более управляемой

2018-10-29 21:11 UTC, SemyonMakhaev commented on index.css
> +    src: url('StudioScriptCTT.woff')  format('woff');
Почему два атрибута `src`? Можно ведь через запятую указать

2018-10-29 21:11 UTC, SemyonMakhaev commented on index.css
> +    src: url('StudioScriptCTT.eot');
Давай добавим ещё `local`, чтобы не загружать шрифт, если он уже есть на компьютере пользователя

2018-10-29 21:11 UTC, SemyonMakhaev commented on index.css
> +    font-size: 20px;
Можно в одно правило `font`

2018-10-29 21:11 UTC, SemyonMakhaev commented on index.css
> +.change:checked ~ main article section p span
Зачем такая вложенность? Достаточно указать правило для родительского элемента, потому что свойство `font-family` наследуется. Аналогично для свойства `font-size` в следующих селекторах

2018-10-29 21:11 UTC, SemyonMakhaev commented on index.html
> +    <meta name="description" content="Сделано по газете &laquo;Новый стандарт&raquo; за сентябрь 2018 г.">
👍

2018-10-29 21:11 UTC, SemyonMakhaev commented on index.html
> +                    <img src="images/Занятия.jpg" alt="Занятия в парке" title="Занятия в парке">
Картинки, кажется, не доехали. Ты не забыла их добавить в коммит?

2018-11-01 05:48 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-01 06:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-01 06:01 UTC, AirenLaird commented
Благодарю) 🔔 по комментариям:
Сделала вертикальный текст.
У меня одна цитата человека, выделила ее в <blockquote>, а человека - в <cite>. Остальные слова, выделенные в тексте кавычками ограничила тегом <q>.
Из селекторов по тегу оставила только span.
1) Указала src через запятую, но линтинг не разрешил мне после запятой делать перенос строки, только перед указанием формата;
2) Добавила local;
3) Добавила везде, стиль, размер и семейство в одно правило font, кроме span (ведь там мне не нужно семейство, а без него в одно правило не доопределить);
4) На счет вложенности, она необходима, иначе классы будут перекрывать родительский тег, пока я не укажу потомков явно. Как это обойти? !important не помогает..
5) 😊
6) Запушила картинки, которые забыла. Я и шрифт наверное забыла, что скачала в двух форматах.. Всё запушила.
Изменила background на background-color, где цвет является одним свойством фона.

2018-11-01 06:10 UTC, AirenLaird commented on index.css
> +.change:checked ~ main article section p span
Из того что я вижу, наследуется только в том случае, если мы не указывали класс для потомков...

2018-11-01 19:41 UTC, SemyonMakhaev commented on index.css
> +.change:checked ~ main article section p span
Ты имеешь ввиду, что эти стили где-то переназначены?

2018-11-01 19:54 UTC, SemyonMakhaev requested changes
🍅 

Всё удачно, остаётся только вопрос насчёт селекторов с большой вложенностью

2018-11-03 11:10 UTC, SemyonMakhaev approved these changes
🍏 

Обсудили лично, решили остановиться на исходном варианте селектора, чтобы не менять `font-family`

2018-11-03 11:10 UTC, closed without merging