solve extra task
urfu-2018/markup-task-3 pull request #103
Opened 2018-10-23 12:20 UTC by HEXBATAET

2018-10-23 12:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 08:36 UTC, mokhov commented
<img width="239" alt="delorean dmc-12 2018-10-29 13-36-06" src="https://user-images.githubusercontent.com/357689/47638162-9d3ab500-db7f-11e8-87de-54f61bb1b0df.png">

Не красиво

2018-10-29 08:38 UTC, mokhov requested changes
Как-то немного не хватает любви 🍅

2018-10-29 08:38 UTC, mokhov commented on index.html
> +                            здание 88.</span> Телефон для предзаказа: <span class="phone">88005553535</span>.
Лучше использовать тег a

2018-10-29 08:38 UTC, mokhov commented on index.html
> +                    Не&shy;кий Эм&shy;мет Бра&shy;ун утвер&shy;жда&shy;ет, что при&shy;ду&shy;ман&shy;ный 30
А почему только здесь прогнал через типограф?

2018-10-29 14:35 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-13 12:49 UTC, closed without merging