Ромасс Ольга
urfu-2018/markup-task-3 pull request #16
Opened 2018-10-21 05:27 UTC by romassol

[Посмотреть решение](https://hruview.herokuapp.com/romassol/markup-task-3/master/index.html)

2018-10-21 05:27 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 17:45 UTC, spt30 requested changes
🍅Привет! Очень красиво выглядит верстка, мне понравилось, ты молодец!

Есть несколько замечаний по css, по семантике немного
И пройдись, пожалуйста, по условию задачи еще раз, там есть пункты, они все обязательные
Без них не зачту)

По поводу дедлайна: 2 дня 7 часов у тебя было в запасе + неделя моя -> дедлайн до 9 ноября 6:00

2018-10-30 17:45 UTC, spt30 commented on index.css
> +    font-size: 610%;
Почему не пиксели?)
Шрифт в общем случае в пикселях задают, если нет обоснований на другие единицы измерения

2018-10-30 17:45 UTC, spt30 commented on index.css
> +.mainHeader
Не именую классы в camelCase, лучше что-то вроде `main-header`

2018-10-30 17:45 UTC, spt30 commented on index.css
> +    padding-bottom: .3%;
Давай все в пикселях)

2018-10-30 17:45 UTC, spt30 commented on index.css
> +.newspaper h2:after
Это псевдоэлемент, а не псевдокласс

2018-10-30 17:45 UTC, spt30 commented on index.css
> +    column-count: 2;
threeColumns -> column-count: 2
немного не логично)

2018-10-30 17:45 UTC, spt30 commented on index.html
> +        <section class="newspaper">
Не вкладывай article в section, лучше наоборот

2018-10-30 17:45 UTC, spt30 commented on index.html
> +        <header class="mainHeader">
header, main и footer, если они есть на странице, должны лежать плоско относительно друг друга

2018-10-30 17:45 UTC, spt30 commented on index.html
> +                <img class="postcard" src="1.jpg" alt="1">
что за alt такой?

2018-10-30 17:45 UTC, spt30 commented on index.html
> +                <header>
header должен быть один на странице
лучше просто пиши h2

2018-11-02 06:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-04 23:07 UTC, spt30 commented
🍏 Забавная функция увеличения текста получилась)))))

2018-11-04 23:07 UTC, closed without merging