газета + доп задание
urfu-2018/markup-task-3 pull request #20
Opened 2018-10-21 11:38 UTC by BlokhinaElizaveta

2018-10-21 11:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 10:32 UTC, nex2hex requested changes
🍅 
Текст рекомендую прогонять через типограф https://www.artlebedev.ru/typograf/

2018-10-23 10:32 UTC, nex2hex commented on index.css
> +.setting
settings

2018-10-23 10:32 UTC, nex2hex commented on index.css
> +    color: rgb(189, 188, 125);
какая-то смесь из формата записей цветов. То так #333224 , то так rgb(189, 188, 125); Давай делать одинаково

2018-10-23 10:32 UTC, nex2hex commented on index.css
> +p
давай именовать блоки по БЭМу
писать стили для тэгов - неудобно и сложно тем, что их приходится постоянно перекрывать и сбрасывать

Например тут https://github.com/urfu-2018/markup-task-3/pull/20/files#diff-bca1542f88ef8253c16b452e9ad09f98R75 и тут
https://github.com/urfu-2018/markup-task-3/pull/20/files#diff-bca1542f88ef8253c16b452e9ad09f98R102

2018-10-23 10:32 UTC, nex2hex commented on index.css
> +    border-style: solid;
вместо трех стилей лучше писать 1 полный 
`border: initial solid rgb(228, 226, 139)`

ниже по коду такие места еще встречаются

2018-10-23 10:32 UTC, nex2hex commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=UnifrakturCook:700" rel="stylesheet">
можно подключать одним файлом сразу

2018-10-23 10:32 UTC, nex2hex commented on index.html
> +    <div class="newspaper">
<section>

2018-10-23 10:32 UTC, nex2hex commented on index.css
> +.content .block
block - очень общее название для класса
старайся давать такие названия, чтобы было понятно что это за блок и как используется

2018-10-23 10:32 UTC, nex2hex commented on index.html
> +                <h3>На Новый год в Севастополе дадут горячую воду!</h3>
каждую статью можно обернуть в article?

2018-10-23 10:32 UTC, nex2hex commented on index.html
> +                <p lang="ru">
атрибут lang надо указать у всего html документа
https://www.w3.org/International/questions/qa-html-language-declarations

2018-10-23 18:53 UTC, BlokhinaElizaveta commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=UnifrakturCook:700" rel="stylesheet">
Как?
`<link href="https://fonts.googleapis.com/css?family=Gabriela|Neucha" rel="stylesheet">` если пишу так, то lint не проходит

2018-10-23 19:00 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 19:01 UTC, BlokhinaElizaveta commented
:green_apple: поправила

2018-10-26 11:44 UTC, nex2hex commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=UnifrakturCook:700" rel="stylesheet">
да, так. Какую ошибку пишет?

2018-10-26 11:45 UTC, nex2hex commented
Текст через https://www.artlebedev.ru/typograf/ забыла

2018-10-26 11:46 UTC, closed without merging

2018-10-26 11:47 UTC, nex2hex commented on index.html
> +                <img src="https://www.ubackground.com/_ph/13/199527334.jpg" alt="clock">
у картинок надо задавать width height чтобы контент не прыгал в момент загрузки картинки

2018-10-26 19:51 UTC, BlokhinaElizaveta commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=UnifrakturCook:700" rel="stylesheet">
> Error: Bad value “https://fonts.googleapis.com/css?family=UnifrakturCook:700|Ruslan+Display” for attribute “href” on element “link”: Illegal character in query: “|” is not allowed.

2018-10-26 20:55 UTC, nex2hex commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=UnifrakturCook:700" rel="stylesheet">
попробуй так https://stackoverflow.com/questions/22466913/google-fonts-url-break-html5-validation-on-w3-org?answertab=votes#tab-top