Логинов Андрей
urfu-2018/markup-task-3 pull request #3
Opened 2018-10-18 18:56 UTC by AndrewLoginov

Решение с доп заданием

2018-10-18 18:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 05:36 UTC, mokhov commented
Вижу две проблемки: нет переноса строка и полоса справа
<img width="418" alt="document 2018-10-29 10-35-39" src="https://user-images.githubusercontent.com/357689/47631129-6d32e800-db66-11e8-8b83-7b2791d490e6.png">

2018-10-29 05:57 UTC, mokhov requested changes
Есть куда стремиться 🍅

2018-10-29 05:57 UTC, mokhov commented on index.css
> +    display: grid;
Задание можно решить без гридов

2018-10-29 05:57 UTC, mokhov commented on index.css
> +    font-family: 'Fascinate Inline', cursive;
Можно использовать просто `font`

2018-10-29 05:57 UTC, mokhov commented on index.html
> +    <label class="input1" for="name6">Основной размер</label>
Зачем здесь классы?

2018-10-29 05:57 UTC, mokhov commented on index.html
> +            <p>Amazing adventure</p>
Это, скорее всего, больше похоже на меню чем на набор текстов

2018-10-29 05:57 UTC, mokhov commented on index.html
> +                <h2 class="news_h2">Lucky horseshoe
Не очень понятен смысл в имени класса держать тег, это и не семантично и странно. `news_header` будет гораздо читаемее

2018-10-29 05:57 UTC, mokhov commented on index.html
> +                    <p class="news_p">In fact, neither in America nor in the Wild
Зачем нужен `p` внутри `blockquote`?

2018-10-29 05:57 UTC, mokhov commented on index.html
> +            <img src="img/6.jpg" alt="man">
Нет размеров и хорошо бы `alt` почитаемее

2018-10-29 05:58 UTC, mokhov commented
И ещё не вижу вот этого условия
Изредка текст пишут:
В
О
Т

Т
А
К

2018-10-31 06:12 UTC, AndrewLoginov commented on index.html
> +                    <p class="news_p">In fact, neither in America nor in the Wild
На MDN и htmlbook в blockquote везде p ставят. + атрибут  cite автоматически на новую строку переносится. Как лучше все же?

2018-10-31 06:14 UTC, AndrewLoginov commented on index.html
> +                <h2 class="news_h2">Lucky horseshoe
Верно, исправлю

2018-10-31 06:15 UTC, AndrewLoginov commented on index.html
> +            <p>Amazing adventure</p>
Нужно же газету сверстать было. Я и не подумал о меню. Окей , исправлю

2018-10-31 06:27 UTC, AndrewLoginov commented on index.html
> +            <img src="img/6.jpg" alt="man">
Размер width: 100%; height: 100%;  ,  поместил в родительский блок как бэкграунд, чтобы при изменении цветовой темы, была возможность менять цвет картинки.

2018-10-31 07:46 UTC, AndrewLoginov commented on index.css
> +    display: grid;
Полосу справа убрал. По поводу мягких переносов, не нашел ни одного сайта, который адекватно расставляет мягкие переносы, либо они вообще не работают. Убрал break-all.

2018-10-31 08:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-13 12:53 UTC, closed without merging