Начнём
urfu-2018/markup-task-3 pull request #31
Opened 2018-10-21 17:43 UTC by VA-Chusovitin

2018-10-21 17:43 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 17:55 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 18:02 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 18:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-21 18:12 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 06:01 UTC, mokhov requested changes
Не понятно куда пропал тег `<h2>`, нет вертикального текста. В остальном всё очень неплохо 🍅

2018-10-29 06:01 UTC, mokhov commented on index.css
> +    float: right;
А про `float` мы ещё не рассказывали

2018-10-29 06:01 UTC, mokhov commented on index.css
> +figure.cyber-security
Зачем нужен селектор тега?

2018-10-29 06:01 UTC, mokhov commented on index.html
> +    <input id="fs1" type="radio" name="font size" checked="checked">
Не понятно зачем эта экономия на названии id?

2018-10-29 06:01 UTC, mokhov commented on index.html
> +        <div class="newspaper-title">
Зачем здесь `div`?

2018-10-29 07:33 UTC, VA-Chusovitin commented on index.html
> +        <div class="newspaper-title">
Ой, забыл убрать.

2018-10-29 07:33 UTC, VA-Chusovitin commented on index.css
> +figure.cyber-security
Чтобы картинку на все столбики растянуть. Или есть способ лучше?

2018-10-29 10:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-13 12:53 UTC, closed without merging