Дерендеева Настя
urfu-2018/markup-task-3 pull request #32
Opened 2018-10-21 17:49 UTC by DerendeevaNastya

2018-10-21 17:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 21:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:36 UTC, nex2hex requested changes
🍅 
по БЭМу классы будем именовать? (upd: можно не делать)

2018-10-23 11:36 UTC, nex2hex commented on index.css
> +    background-color: beige;
можно записать короче через 
```
background: beige url(...) 0 0 no-repeat;
background-size: 100%;
```

2018-10-23 11:36 UTC, nex2hex commented on index.css
> +    src: url('fonts/coolFont.TTF');
ttf? почему на woff2/woff?

2018-10-23 11:36 UTC, nex2hex commented on index.html
> +            <img src="images/horklump.jpg" alt="horklump">
у картинок надо задавать width height чтобы контент не прыгал в момент загрузки картинки

2018-10-23 11:36 UTC, nex2hex commented on index.html
> +                Мурлокомль (англ. Horklump) - происходит из Скандинавии, в настоящее время распространен
текст лучше прогонять через типограф, тогда переносы будут нормальные https://www.artlebedev.ru/typograf/

2018-10-23 11:50 UTC, nex2hex commented
И самое главное - задачу нужно делать через https://webref.ru/css/columns

2018-10-29 16:36 UTC, DerendeevaNastya commented on index.css
> +    src: url('fonts/coolFont.TTF');
надо переделать с ttf на woff? почему нельзя ttf?

2018-10-29 16:45 UTC, nex2hex commented on index.css
> +    src: url('fonts/coolFont.TTF');
См https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/webfont-optimization?hl=ru

`Форматы EOT и TTF не сжимаются по умолчанию.`

2018-10-29 17:05 UTC, DerendeevaNastya commented on index.html
> +            <img src="images/horklump.jpg" alt="horklump">
необходимо задать статичные размеры (не с процентами?) и прямо здесь, а не в css?

2018-10-29 17:11 UTC, nex2hex commented on index.html
> +            <img src="images/horklump.jpg" alt="horklump">
да, просто размеры в пикселях
`<img src="images/horklump.jpg" width="100" height="23" alt="horklump">`

2018-10-29 18:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 11:00 UTC, nex2hex requested changes
🍅

2018-10-30 11:00 UTC, nex2hex commented on index.css
> +    src: url('fonts/coolFont.woff');
см https://urfu-2018.github.io/slides/markup/03-fonts-and-text/index.pdf

там есть слайд как подключать шрифты

Сейчас у тебя не хватает woff2 для новых браузеров

2018-10-30 11:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 12:05 UTC, nex2hex commented on index.css
> +    src: url('fonts/coolFont.woff') format('woff'), url('fonts/coolFont.ttf') format('ttf'), url('fonts/coolFont.woff2') format('woff2');
при таком подходе у тебя будет:
1) знаешь woff? грузи его
2) если нет, то знаешь ttf? используй его
3) ttf нет? тогда woff2

посколько все браузеры, которые умеют woff2 умеют и woff, то woff2 по факту использоваться никогда не будет

2018-10-30 15:35 UTC, DerendeevaNastya commented on index.css
> +    src: url('fonts/coolFont.woff') format('woff'), url('fonts/coolFont.ttf') format('ttf'), url('fonts/coolFont.woff2') format('woff2');
в таком порядке надо: woff2/woff/ttf?

2018-11-06 11:08 UTC, nex2hex commented on index.css
> +    src: url('fonts/coolFont.woff') format('woff'), url('fonts/coolFont.ttf') format('ttf'), url('fonts/coolFont.woff2') format('woff2');
в большинстве случаев достаточно просто woff2/woff

2018-11-06 11:08 UTC, closed without merging