Солодовникова Екатерина
urfu-2018/markup-task-3 pull request #4
Opened 2018-10-19 09:25 UTC by KatySolo

[Посмотреть решение](https://hruview.herokuapp.com/KatySolo/markup-task-3/master/index.html)

2018-10-19 09:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-28 06:18 UTC, chrighter requested changes
🍅

2018-10-28 06:18 UTC, chrighter commented on index.css
> +.verticalLabel
Давай именовать классы не в `camelCase`

2018-10-28 06:18 UTC, chrighter commented on index.css
> +.italy_header
Давай именовать классы не в `snake_case`

2018-10-28 06:18 UTC, chrighter commented on index.html
> +    <span>Выбирете режим чтения</span>
Выберите

2018-10-28 06:18 UTC, chrighter commented on index.html
> +        <input type="radio" name="readingMode" value="night" id="nightModeRadio">
Давай еще на кликабельные элементы `cursor: pointer` делать

2018-10-28 06:18 UTC, chrighter commented on index.html
> +                <img src="pictures/italy.png" alt="Italy">
Точно нужен еще один отступ?

2018-10-28 06:18 UTC, chrighter commented on index.html
> +                    Италия знаменита огромным количество местных сортов винограда
Повторение задумано?)

2018-10-28 06:18 UTC, chrighter commented on index.css
> +
Лишний отступ

2018-10-28 06:18 UTC, chrighter commented on index.css
> +    text-orientation: upright;
👍

2018-10-28 06:18 UTC, chrighter commented on index.css
> +
Отступ

2018-10-28 06:18 UTC, chrighter commented on index.html
> +                    <img src="pictures/france.png" alt="France">
Давай еще подпись к картинке добавим

2018-10-28 19:30 UTC, KatySolo commented on index.html
> +                    Италия знаменита огромным количество местных сортов винограда
Вообще да, просто я не знала где взять еще текста) Если это критично, то я могу передалать на другой текст)

2018-10-28 20:10 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 05:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 09:52 UTC, chrighter approved these changes
🍏

2018-10-30 09:52 UTC, closed without merging