Решение задачи без допа
urfu-2018/markup-task-3 pull request #40
Opened 2018-10-22 06:52 UTC by AIBarabanshchikova

2018-10-22 19:54 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 20:31 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 04:39 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 07:02 UTC, AIBarabanshchikova commented
+ сделано доп. задание

2018-10-29 07:44 UTC, mokhov commented
<img width="405" alt="delorean dmc-12 2018-10-29 12-07-43" src="https://user-images.githubusercontent.com/357689/47634418-4cbd5a80-db73-11e8-9c46-4bd7afd518ac.png">
Некрасиво

2018-10-29 07:46 UTC, mokhov requested changes
В целом очень неплохо, но чуть-чуть нужно доделать
🍅

2018-10-29 07:46 UTC, mokhov commented on index.css
> +    display: flex;
Это задание можно решить без использования flex

2018-10-29 07:46 UTC, mokhov commented on index.css
> +    background: url(http://ekladata.com/4z74jKsN6kAKZIuPGsNi2Jpe1vc.jpg);
Это работает, но впредь лучше грузить картинки через тот же протокол где будет задание. А на github это https

2018-10-29 07:46 UTC, mokhov commented on index.css
> +span.theme
А зачем здесь селектор тега?

2018-10-29 09:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 09:17 UTC, AIBarabanshchikova commented
🍏

2018-11-13 12:52 UTC, closed without merging