Доработки
urfu-2018/markup-task-3 pull request #45
Opened 2018-10-22 12:54 UTC by Kuvadorian

2018-10-22 18:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 10:49 UTC, msmirnov requested changes
🍅 
Ночной режим не работает, текст не видно

2018-10-23 10:49 UTC, msmirnov commented on index.html
> +    <input class="inputAverageFont" type="radio" name="fontSize" id="average">
Именовать классы правильнее не в camelCase, а в kebab-case. Это негласное правило, но все его придерживаются. Про именование классов можно почитать вот тут: https://ru.bem.info/methodology/naming-convention/

2018-10-23 10:49 UTC, msmirnov commented on index.html
> +    <label class="fantasy" for="fantasy">Fantasy</label>
Не понравилось, что при загрузке страницы, ни один из радио не выбран. Получается, что попереключав шрифт, я не могу вернуться к начальному состоянию. Надо либо по дефолту сделать arial, либо добавить третий пункт с дефолтным шрифтом

2018-10-23 10:49 UTC, msmirnov commented on index.css
> +    position: absolute;
Колонки на абсолютах это плохо, нужно переделать.

2018-10-23 10:50 UTC, msmirnov commented
Еще не нравится, что на всей странице есть горизонтальный скролл, его там быть не должно

2018-10-23 15:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 15:11 UTC, Kuvadorian commented
🍏

2018-10-24 06:38 UTC, msmirnov approved these changes

2018-10-24 06:38 UTC, closed without merging