Роговой Арсений
urfu-2018/markup-task-3 pull request #48
Opened 2018-10-22 15:27 UTC by mrkvinter

[Посмотреть решение](https://hruview.herokuapp.com/mrkvinter/markup-task-3/master/index.html)

2018-10-22 19:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 10:53 UTC, msmirnov requested changes
🍅

2018-10-23 10:53 UTC, msmirnov commented on index.html
> +    <input type="radio" name="font_size" value="low">Маленький<br>
Нужно, чтобы подписи к инпутам тоже были кликабельные, так будет приятнее пользователям

2018-10-23 10:53 UTC, msmirnov commented on index.html
> +    <input type="radio" name="font_type" value="monospace">Monospace<br>
Дефолтный шрифт никак не выбран, получается что после изменения шрифта, я никак не могу откатиться на начальное состояние.

2018-10-23 18:50 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-24 06:40 UTC, msmirnov approved these changes

2018-10-24 06:40 UTC, closed without merging