Рожков Максим
urfu-2018/markup-task-3 pull request #51
Opened 2018-10-22 17:25 UTC by MaximRhz

[Посмотреть решение](https://hruview.herokuapp.com/MaximRhz/markup-task-3/master/index.html)

2018-10-22 19:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-28 18:35 UTC, chrighter requested changes
🍅

2018-10-28 18:35 UTC, chrighter commented on index.css
> +.mainHeader
Давай писать `css`-классы не в `camelCase`

2018-10-28 18:35 UTC, chrighter commented on index.css
> +    border-bottom: 1px solid #242121;
Иногда цвета в `hex`, иногда в `rgb`, давай сделаем единообразно

2018-10-28 18:35 UTC, chrighter commented on index.css
> +.rub
Непонятное именование

2018-10-28 18:35 UTC, chrighter commented on index.css
> +.rub
Предполагалось использование `writing-mode` и `text-orientation`

2018-10-28 18:35 UTC, chrighter commented on index.html
> +        <header class="head">ЕКАТЕРИНБУРГ, СРЕДА, ОКТЯБРЬ 31, 2018, ОДНА СТРАНИЦА</header>
На странице не может быть 2 хедэра

2018-10-28 18:35 UTC, chrighter commented on index.html
> +                <img class="leftimg"
Давай не будем называть классы `css`- свойствами

2018-10-28 18:35 UTC, chrighter commented on index.html
> +                        Мар&shy;тин Шей&shy;мус Мак&shy;флай бо&shy;лее из&shy;вест&shy;ный
Неправильная табуляция

2018-10-28 18:35 UTC, chrighter commented on index.html
> +                        <img class="docAndMarty"
Тоже беда с табуляцией

2018-10-28 18:35 UTC, chrighter commented on index.css
> +    float: left;
Чтобы контент "не прыгал" при загрузке страницы, нужно указать ей размер

2018-10-28 18:35 UTC, chrighter commented on index.css
> +    filter: grayscale(100%);
👍

2018-11-03 13:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-03 13:28 UTC, MaximRhz commented on index.css
> +    float: left;
Указал размеры, но вроде не помогло

2018-11-03 13:29 UTC, MaximRhz commented on index.css
> +    filter: grayscale(100%);
Можешь закрыть второй маркап?)

2018-11-08 15:08 UTC, closed without merging