Раджабов Роман
urfu-2018/markup-task-3 pull request #52
Opened 2018-10-22 17:39 UTC by RadzhabovRoman

Гитхаб живи

2018-10-22 19:53 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-22 21:16 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 09:04 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-31 18:40 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-19 16:54 UTC, spt30 requested changes
🍅 Привет! Ты сдал задачу за 15 часов до дедлайна, новый до 27 ноября 13:00

Пробегись, пожалуйста, еще раз по условию: все пункты обязательные
И переименуй классы в другом стиле, пожалуйста)

2018-11-19 16:54 UTC, spt30 commented on index.css
> +.columnBOX
Интересный метод наименования классов

2018-11-19 16:54 UTC, spt30 commented on index.css
> +    width: 69%;
что-то не влезло:(

![image](https://user-images.githubusercontent.com/31798669/48720969-b98fb600-ec42-11e8-8da3-d1d5d2229238.png)

2018-11-19 16:54 UTC, spt30 commented on index.css
> +
строчка лишняя

2018-11-19 16:54 UTC, spt30 commented on index.html
> +    <h1>СПОРТИВНЫЕ ИГРЫ В ШКОЛАХ</h1>
Хотелось бы, чтобы тут был обычный текст, а регистр для оформления задан с помощью стилей

2018-11-19 16:54 UTC, spt30 commented on index.html
> +                <span class="firstLetterIntro">Т</span>а&shy;кое по&shy;ло&shy;же&shy;ние
Есть специальный псевдоэлемент для первой буквы, используй его

2018-11-19 16:54 UTC, spt30 commented on index.html
> +                <p>Б</p>
Есть способ это тоже сделать с помощью css

2018-11-24 13:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-24 18:20 UTC, spt30 commented on index.html
> +    <h1>СПОРТИВНЫЕ ИГРЫ В ШКОЛАХ</h1>
Это не поправлено, но раз ты не поправил, то можешь в будущем сам разобраться, как это делать

2018-11-24 18:27 UTC, spt30 commented
🍏 основные моменты поправлены, молодец)

2018-11-24 18:27 UTC, closed without merging