Афанасьев Леонид
urfu-2018/markup-task-3 pull request #55
Opened 2018-10-22 17:56 UTC by Buka174

2018-10-22 19:58 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-22 19:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 03:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 03:15 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 03:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 03:25 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 07:51 UTC, mokhov requested changes
Есть небольшие замечания 🍅

2018-10-29 07:51 UTC, mokhov commented on index.html
> +    Change font size<input class="checkboxFontSize" type="checkbox">
Нет связки текста с input'ом

2018-10-29 07:51 UTC, mokhov commented on index.html
> +    Black Theme<input class="checkboxBlackTheme" type="checkbox"><br>
Почему здесь camelCase, а дальше нет?

2018-10-29 07:51 UTC, mokhov commented on index.html
> +        <article class="article2">
Очень не говорящее название класса

2018-10-29 07:51 UTC, mokhov commented on index.html
> +                <p class="quote spanning">
Есть более семантичный тег

2018-10-29 07:51 UTC, mokhov commented on index.css
> +.article-contents p:not(.quote):not(.spanning)
Не очень понятно зачем здесь двойное отрицание, если `quote` использовался вместо со `spanning`

2018-10-29 15:52 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-13 12:49 UTC, closed without merging