Жукова Ольга
urfu-2018/markup-task-3 pull request #6
Opened 2018-10-19 15:41 UTC by Ollisteka

2018-10-19 15:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 13:18 UTC, Ollisteka commented
@SemyonMakhaev, вызываю тебя! :bell: (:

2018-10-23 14:31 UTC, SemyonMakhaev requested changes
🍅 

Выглядит классно! Молодец, что следишь за семантикой 👍 

А как же вертикальный текст?
А цитаты?

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.html
> +    <link href="https://fonts.googleapis.com/css?family=Rye" rel="stylesheet">
Давай хотя бы один шрифт подключим через `font-face`, как вам показывали на лекции

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.html
> +    Увеличить шрифт: <input class="zoom" type="checkbox">
А получится ли сделать так, чтобы тема менялась также при нажатии на текст "Сменить тему"? Аналогично про "Увеличить шрифт"

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.html
> +                    Duis nec au&shy;gue nisl. Pel&shy;len&shy;tesque sit amet leo dui.</div>
👍

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.html
> +            <article class="aside">
Неконсистентно)
Так это `article` или всё-таки `aside`?

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.html
> +            <div class="article">
Тоже неконсистентно

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.css
> +input.swap:checked ~ main
Старайся избегать использования тегов в селекторах. Не только в этой ситуации, а вообще. Аналогичного эффекта ты можешь добиться только классами, но при этом твоя вёрстка будет более контролируемой

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.css
> +input.swap:checked ~ main
В селекторе класса не обязательно указывать тег
```suggestion
.swap:checked ~ main
```

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.css
> +    font-family: UnifrakturMaguntia;
Основной шрифт лучше указать у `body`, для остальных элементов он унаследуется

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.css
> +    margin-bottom: 10px;
Можно в одно правило с использованием свойства `margin`

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.css
> +    float: left;
Получится ли здесь обойтись без `float`?

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.css
> +    font-family: Rye;
Это правило есть в селекторе выше. Можно сгруппировать селекторы

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.css
> +    text-align: center;
Правило очень часто используется. Можно вынести в отдельный класс

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.css
> +    float: left;
Аналогично про `float`

2018-10-23 14:31 UTC, SemyonMakhaev commented on index.html
> +                <img alt="Грустный Леопольд" width="250" height="150"
Не расстраивай Леопольда, обязательно всегда добавляй `title` для `img`

2018-10-23 16:56 UTC, Ollisteka commented on index.html
> +            <article class="aside">
Это статья, которая расположена сбоку))

2018-10-23 17:56 UTC, Ollisteka commented on index.css
> +    font-family: UnifrakturMaguntia;
Но это не основной шрифт... :thinking:

2018-10-23 18:06 UTC, Ollisteka commented on index.css
> +    float: left;
У меня пока не получается :(

2018-10-23 18:07 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 18:09 UTC, Ollisteka commented
Цитат добавлю позже :)

2018-10-24 15:40 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-24 15:48 UTC, Ollisteka commented
@SemyonMakhaev, сделала правки по ревью :)

2018-10-27 11:07 UTC, SemyonMakhaev commented on index.css
> +    font-family: UnifrakturMaguntia;
А который основной? Вот он должен быть у `body` 😄

2018-10-27 11:25 UTC, SemyonMakhaev requested changes
🍅

2018-10-27 11:25 UTC, SemyonMakhaev commented on index.css
> +    src: url(fonts/Rye-Regular.ttf);
Можно использовать `local`. Тогда шрифт загрузится быстрее, если он есть на компьютере пользователя

https://developer.mozilla.org/ru/docs/Web/CSS/@font-face

2018-10-27 11:25 UTC, SemyonMakhaev commented on index.css
> +    src: url(fonts/Charmonman-Regular.ttf);
Аналогично про `local`

2018-10-27 11:25 UTC, SemyonMakhaev commented on index.css
> +[class*='header']
Это неэффективный селектор. Браузер будет искать подстроку во всех атрибутах `class`. Правило будет применяться очень долго и съест много ресурсов клиента, особенно если страница достаточно большая.

Эффективнее будет создать новый класс

2018-10-27 11:25 UTC, SemyonMakhaev commented on index.css
> +    margin: 15px 0 10px;
👍

2018-10-27 11:25 UTC, SemyonMakhaev commented on index.css
> +    float: left;
Можно элементы `two-columns`, `one-column` и вертикальный текст обернуть в общий элемент, для которого задать правило `display: inline-block` и `vertical-align: top`. Те же стили добавить для тега `aside` вместо `float`.

2018-10-28 09:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-28 09:23 UTC, Ollisteka commented
@SemyonMakhaev, я не могу почему-то напрямую на комментарий про `float` ответить, так что тут спрошу. Я смогла от него избавиться, но так и не поняла, чем он плох? С `display` понятней получается? Или есть ещё какая-то причина?
P.S. Всё остальное тоже исправила (:

2018-10-28 12:09 UTC, SemyonMakhaev commented
Насчёт `float` - он ничем не плох, просто он применяется для элементов, которые имеют "плавающую природу", когда нужно реализовать какое-то обтекание.

`float` не применяется для того, чтобы расставить несколько блочных элементов в одну строку. Эта задача решается либо при помощи `display: inlie-block` и `vertical-align`, либо новыми прогрессивными технологиями, о которых вам расскажут на одной из следующих лекций: `display: flex`

2018-10-28 12:14 UTC, SemyonMakhaev approved these changes
🍏 

Молодец!

2018-10-28 12:14 UTC, SemyonMakhaev commented on index.css
> +    src: local('Rye'), local('Rye Regular'), local('Rye-Regular'), url(fonts/Rye-Regular.ttf);
👍

2018-10-28 12:14 UTC, SemyonMakhaev commented on index.css
> +    src: local('Charmonman Regular'), local('Charmonman-Regular'), url(fonts/Charmonman-Regular.ttf);
Также для обеспечения кроссбраузерности имеет смысл подключать несколько форматов шрифтов, по крайней мере, `woff` и `woff2`

2018-10-28 12:14 UTC, closed without merging