Анисимов Данил
urfu-2018/markup-task-3 pull request #70
Opened 2018-10-23 00:33 UTC by frosthamster

2018-10-23 00:33 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 00:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 00:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 18:28 UTC, SemyonMakhaev requested changes
🍅 

Привет! Извини за долгое ревью.

Круто, что сделал вертикальный текст и настраиваемые параметры!
В основном задании сказано, что нужно добавить цитаты в текст.

Старайся избегать селекторов по тегу. Селекторы классов делают твою вёрстку более управляемой

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +    src: url(fonts/KingArthur.ttf);
Давай подключим ещё `local`, чтобы не загружать шрифт, если он уже есть на компьютере у пользователя

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +    src: url(fonts/KingArthur.ttf);
Будет здорово, если подключишь ещё пару форматов шрифта для обеспечения кроссбраузерности. Например, `woff` и `woff2`

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +    background: url(resources/background.jpg);
Для задания изображения достаточно использовать `background-image`

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +    font-size: 1.5em;
Давай в одно правило - `font`

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +    text-align: center;
Правило дублируется. Нужно либо вынести в отдельный класс, либо сгруппировать селекторы

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +    margin-bottom: 16px;
Лучше указать в одно правило, это упрощает чтение кода

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +input[class='change_font_size']:checked ~ .newspaper
```suggestion
.change_font_size:checked ~ .newspaper
```

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +input[class='change_color']:checked ~ .newspaper p::first-letter
Селектор можно сгруппировать с соседним, в строке [200](https://github.com/urfu-2018/markup-task-3/pull/70/files#diff-bca1542f88ef8253c16b452e9ad09f98R200). Правила полностью совпадают

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.css
> +    background: #806917;
`background-color`

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.html
> +                <img src="resources/forest.jpg" title="forest" alt="forest">
👍

2018-10-29 18:28 UTC, SemyonMakhaev commented on index.html
> +            <p lang="en">Pellentesque nibh quam, iaculis ut ipsum eget, blandit ornare nisi. Nunc porta lacus
Зачем указывать язык для элемента, если он совпадает с тем, который указан глобально для `html`?

2018-10-29 18:46 UTC, frosthamster commented on index.html
> +            <p lang="en">Pellentesque nibh quam, iaculis ut ipsum eget, blandit ornare nisi. Nunc porta lacus
вроде, чтобы работали переносы через hyphens: auto
или это не так работает?

2018-10-29 18:50 UTC, frosthamster commented
Цитата сделана, возможно, она не слишком кохошо выделена
класс .cite
![image](https://user-images.githubusercontent.com/17183342/47673050-57a8d700-dbd5-11e8-80a7-61cdbd54efd0.png)

2018-10-29 18:51 UTC, SemyonMakhaev commented
> Цитата сделана

Ок, давай тогда для неё семантичный тег используем)

2018-10-29 18:52 UTC, frosthamster commented
понял, будет

2018-10-30 18:34 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 18:35 UTC, frosthamster commented
честно пытался найти хотя бы один из шрифтоф в woff/woff2, не нашёл

2018-10-30 18:43 UTC, frosthamster commented
> 
> 
> честно пытался найти хотя бы один из шрифтоф в woff/woff2, не нашёл

звто нашёл конвертер ttf -> woff

2018-10-30 18:43 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 20:17 UTC, SemyonMakhaev commented on index.html
> +            <p lang="en">Pellentesque nibh quam, iaculis ut ipsum eget, blandit ornare nisi. Nunc porta lacus
По умолчанию браузер возьмёт язык из тега `html`

http://htmlbook.ru/css/hyphens

2018-10-30 20:22 UTC, SemyonMakhaev approved these changes
🍏

2018-10-30 20:22 UTC, SemyonMakhaev commented on index.css
> +    src: local('King Atrhur'), url(fonts/KingArthur.woff2) format('woff2'), url(fonts/KingArthur.woff) format('woff'), url(fonts/KingArthur.ttf) format('truetype');
👍

2018-10-30 20:23 UTC, closed without merging