The first attempt
urfu-2018/markup-task-3 pull request #73
Opened 2018-10-23 06:17 UTC by Nerzull3

2018-10-23 06:18 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 06:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-10 11:54 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 11:58 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-10 12:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-11-10 12:13 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-25 14:07 UTC, spt30 requested changes
🍅 Привет! Ты сдал задачку за 6 часов до дедлайна, новый до 3 декабря 01:00

P.S. не хватает пункта про картинку на несколько колонок, но тут ее вставлять особо некуда по смыслу, так что если надо будет – разберешься, как вставить

2018-11-25 14:07 UTC, spt30 commented on index.css
> +.top-angle
Даже внутри хэдера плохо называть классы по расположению
Лучше по контенту

2018-11-25 14:07 UTC, spt30 commented on index.css
> +    margin: 0 10%;
тут вот смотри, какая петрушка получается:
<img width="1426" alt="2018-11-25 18 32 38" src="https://user-images.githubusercontent.com/31798669/48979690-833db500-f0e0-11e8-90cf-3cd720d9093b.png">
Это из-за плохих размеров

1) Есть замечательное свойство box-sizing, если ты его выставишь в border-box, то размеры элемента будут считаться с учетом паддингов и границ,
2) Для центрирования выставлять margin явно – плохая политика, лучше сделать `margin: 0 auto;`
3) Обязательно в 99% случаев выставлять паддинги по краям, чтобы контент не прилипал к границе экрана
4) Судя по тому, что ниже у тебя выставлены width и height для блочков по 8%, то, вероятно, ты хотел их сделать квадратными, но, увы, значение ширины берется от ширины, а высоты – от высоты))

Соответственно, чтобы тут хорошо разложить контент, нужно:
а) выставить значения ширины и высоты у блочков по краям в пикселях
б) сделать header'у оступы по краям, чтобы не прилипал контент (остальным блокам на странице желательно тоже)
в) сделать заголовку `margin: 0 auto;`
г) сделать заголовку паддинги хотя бы по 10-20 рх, чтобы заголовок не лип к блочкам
P.S. можешь убрать объемлющие дивы у параграфов и заголовка, они ничего не делают

2018-11-25 14:07 UTC, spt30 commented on index.css
> +    font: 28px bold;
здесь не критично, но на будущее лучше разделять на личные свойства: font-size и font-weight

если я напишу `animation: moveToTop .3s ease-in-out .7s infinite alternate-reverse backwards paused;`, это будет валидное css-свойство, но ничего ж не понятно)

2018-11-25 14:07 UTC, spt30 commented on index.css
> +    column-count: 3;
![image](https://user-images.githubusercontent.com/31798669/48979896-6f478280-f0e3-11e8-831a-42462b43d3e5.png)
Кажется, это свойство тебя очень подвело)
Тут тоже интересное поведение, ширина параграфа в 100% взялась от ширины колонки, на которые ты разделил, поэтому так и поехало
Не ручаюсь за то, что во всех браузерах так считается, но лучше убрать это свойство и оставить просто width:100%, а text-align'ом выравнивать, что ты и сделал, молодец)

2018-11-25 14:07 UTC, spt30 commented on index.css
> +    display: inline-block;
Из-за этого свойства у тебя margin'ы не схлопываются, это нарочно так?

2018-11-25 14:07 UTC, spt30 commented on index.css
> +.Earthday-content
не завязывайся на содержание, если тебе редактор газеты скажет поменять статью на другую, будешь менять название класса?)

2018-11-25 14:07 UTC, spt30 commented on index.css
> +input[value='Times-New-Roman-style']:checked ~ .newspaper-content
можно через запятую перечислить навроде:
```
input[value='Times-New-Roman-style']:checked ~ .newspaper-content,
input[value='Times-New-Roman-style']:checked ~ header
{
    ...
};
```

тогда у header'а тоже будет меняться фон, шрифт и пр.

2018-11-25 14:07 UTC, spt30 commented on index.css
> +body > header
Соблюдал-соблюдал порядок стилей, а в конце бац! и `body > header`:(
давай унесем наверх

2018-11-25 14:07 UTC, spt30 commented on index.html
> +<html lang="en">
Респект 👍

2018-11-25 14:07 UTC, spt30 commented on index.html
> +    Режим чтения:
Лучше не оставлять текст просто так, оберни во что-нибудь

2018-11-25 14:07 UTC, spt30 commented on index.html
> +            <header>
Еще один header зачем-то
просто h2 достаточно, кажется

2018-11-25 14:07 UTC, spt30 commented on index.html
> +            <header>
тут тоже

2018-11-25 15:16 UTC, Nerzull3 commented on index.css
> +    margin: 0 10%;
Я изначально сделал в пикселях, но мне не понравилось, что при сужении экрана, эти правый квадрат падал) Решил завязаться на проценты, но, к сожалению, квадраты стали растягиваться. Окей, поправлю

2018-11-25 15:18 UTC, Nerzull3 commented on index.css
> +    column-count: 3;
Эх, а на локальном компьютере всё хорошо было :(

2018-11-25 15:25 UTC, Nerzull3 commented on index.css
> +    column-count: 3;
Изначально было без этих колонок, и текст почему-то был не ровно на одном уровне. Хорошо, переделаю

2018-11-25 15:50 UTC, spt30 commented on index.css
> +    column-count: 3;
Возможно, особенности браузера или ОС, предлагаю не вдаваться в подробности, без column-count смотрится хорошо

2018-11-25 23:41 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-26 19:01 UTC, spt30 commented
Все еще бесит, что нет padding'ов у main и контент прилипает, но ты молодец, прям по коду и правкам грамотным видно, что у тебя есть понимание того, что ты делаешь

Отступы не критично, в следующий раз не забывай про них)

2018-11-26 19:01 UTC, closed without merging

2018-11-26 19:24 UTC, Nerzull3 commented
Да, в header'е поменял, а про main совсем забыл. Учту на будущее, буду исправлять. 

Только есть вопрос: почему без экстры? :(

2018-11-26 20:21 UTC, spt30 commented
Да, экстра, конечно, должна быть, провафлил, думал, что 4-ю проверяю