Mazalov Daniil
urfu-2018/markup-task-3 pull request #74
Opened 2018-10-23 06:18 UTC by danilych-100

2018-10-23 06:19 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-26 10:50 UTC, nex2hex requested changes
🍅

2018-10-26 10:50 UTC, nex2hex commented on index.css
> +    src: url(fonts/Molot.otf) format('opentype');
otf?
давай добавим woff1
про то, как подключать шрифты было в лекции https://urfu-2018.github.io/slides/markup/03-fonts-and-text/index.pdf

2018-10-26 10:50 UTC, nex2hex commented on index.css
> +    font-family: MainHeaderFont;
font-family должен соответствовать имени шрифта, а не то, где он и для чего используется

2018-10-26 10:50 UTC, nex2hex commented on index.html
> +            <img src="img/mainPhoto.jpg" class="main-image" alt="Gagarin">
указывай высоту и ширину картинки, чтобы текст не прыгал во время загрузки страницы

2018-10-26 10:50 UTC, nex2hex commented on index.html
> +                        12 апреля 1961г. в Советском Союзе выведен на орбиту вокруг Земли
Текст можно прогонять через типограф https://www.artlebedev.ru/typograf/

2018-10-26 10:50 UTC, nex2hex commented on index.html
> +        <div class="right-side-text-content">
тут можно использовать тэг arcticle

2018-10-27 13:18 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-27 13:19 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-27 13:22 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 15:23 UTC, nex2hex requested changes
🍅

2018-10-29 15:23 UTC, nex2hex commented on index.css
> +    font-family: Molot;
давай добавим еще woff2
посмотри в лекции, как подключать шрифты

там было про это

2018-10-29 15:23 UTC, nex2hex commented on index.html
> +    <link href="https://fonts.googleapis.com/css" rel="stylesheet">
а это зачем?

2018-10-29 15:23 UTC, nex2hex commented on index.html
> +        ЧЕЛОВЕК В КОСМОСЕ!
чтобы сделать текст заглавными буквами есть свойство https://webref.ru/css/text-transform

2018-10-29 18:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 11:01 UTC, nex2hex commented
🍅 
См https://urfu-2018.github.io/slides/markup/03-fonts-and-text/index.pdf

```
@font-face {
font-family: myCustomFont;
src: url(myCustomFont.woff2) format(woff2),
url(myCustomFont.woff) format(woff)
}
```

2018-10-30 11:59 UTC, danilych-100 commented on index.css
> +    font-family: Molot;
Мне для каждого шрифта что ли сделать woff2, или только для одного достаточно будет?

2018-10-30 12:01 UTC, nex2hex commented on index.css
> +    font-family: Molot;
сделай хотя бы для одного правильно

2018-10-30 12:40 UTC, danilych-100 commented on index.css
> +    font-family: Molot;
я, короче не правильно закомитил(. Исправлю щас

2018-10-30 12:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 12:45 UTC, nex2hex commented
прочитай еще раз мое сообщение выше
woff2 поддерживают не все браузеры
нужен фолбэк на woff

2018-10-30 12:51 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-30 12:51 UTC, closed without merging