Ильиных Иван
urfu-2018/markup-task-3 pull request #82
Opened 2018-10-23 08:58 UTC by evilPaprika

2018-10-23 08:59 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 09:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 10:08 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 10:33 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 10:37 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 08:17 UTC, mokhov requested changes
Нет вертикального текста, а также не используется газетная верстка с разбиением на колонки
🍅

2018-10-29 08:17 UTC, mokhov commented on index.css
> +    border-color: inherit;
Зачем нужно это правило?

2018-10-29 08:17 UTC, mokhov commented on index.css
> +    position: absolute;
Это задание можно решить без `position: absolute`

2018-10-29 08:17 UTC, mokhov commented on index.css
> +    font-family: 'Limelight', cursive;
`family` и `size` можно объединить в одном правиле

2018-10-29 08:17 UTC, mokhov commented on index.html
> +                            <img src="images/oh.jpg" alt="oh oh thats hard">
Содержимо `alt` должно отвечать на вопрос «что находится на картинке?»

2018-10-29 08:17 UTC, mokhov commented on index.html
> +    <footer></footer>
Пустой футер

2018-11-01 11:30 UTC, evilPaprika commented on index.css
> +    border-color: inherit;
Чтобы я мог поменять border-color у main и цвет у его детей тоже поменялся. Это нужно чтобы когда я меняю тему на темную, сделать цвет border светлым и не делать кучу селекторов.

2018-11-01 16:08 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-01 18:36 UTC, evilPaprika commented
🍏

2018-11-13 12:56 UTC, closed without merging