Ратков Максим
urfu-2018/markup-task-3 pull request #83
Opened 2018-10-23 09:00 UTC by mattgroy

2018-10-23 09:01 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-26 11:05 UTC, nex2hex requested changes
🍅

2018-10-26 11:05 UTC, nex2hex commented on index.css
> +{
min-width

2018-10-26 11:05 UTC, nex2hex commented on index.css
> +@import url('https://fonts.googleapis.com/css?family=Caveat|Kelly+Slab|Oswald|Playfair+Display|Russo+One&subset=cyrillic');
подключи один из шрифтов локально

2018-10-26 11:05 UTC, nex2hex commented on index.css
> +    /*даже так переносы не появляются*/
браузер не знает язык la
сделай на en или ru

2018-10-26 11:05 UTC, nex2hex commented on index.css
> +    font-family: 'Russo One', sans-serif;
можно записать одним свойством через font

2018-10-26 11:05 UTC, nex2hex commented on index.css
> +    font-size: 1em;
`font: ...`

2018-10-26 11:05 UTC, nex2hex commented on index.html
> +                Lorem ipsum dolor sit amet, consectetur adipisicing elit.
Текст лучше прогнать через https://www.artlebedev.ru/typograf/

2018-10-26 11:05 UTC, nex2hex commented on index.html
> +                <img src="https://hmp.me/cbqx" alt="Сом Володя">
указывай ширину и высоту у картинок, чтобы страница не прыгала в момент загрузки

2018-10-30 10:01 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 10:03 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 10:09 UTC, mattgroy commented
🔔 линтер ругается на длинные строки в css, если на несколько строк разделить, то ругается, что нет обрамляющего пробела после запятых, хотя в коммите они есть. Что делать в такой ситуации?

2018-10-30 11:04 UTC, nex2hex commented
1) поправь длину строки в https://github.com/urfu-2018/markup-task-3/blob/master/.htmllintrc

2)
См https://urfu-2018.github.io/slides/markup/03-fonts-and-text/index.pdf

```
@font-face {
    font-family: myCustomFont;
    src: url(myCustomFont.woff2) format(woff2),
    url(myCustomFont.woff) format(woff)
}
```

2018-11-01 05:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-06 12:44 UTC, nex2hex commented
woff формата не хватает

2018-11-06 12:44 UTC, closed without merging