markup-task-3 (0)
urfu-2018/markup-task-3 pull request #88
Opened 2018-10-23 10:46 UTC by zarix908

2018-10-23 10:47 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-23 11:47 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 08:18 UTC, mokhov requested changes
Вертикальный текст выглядит плохо. Изменения шрифта не работает. Могу принять но без допа, или надо доделать
🍅

2018-10-29 08:18 UTC, mokhov commented on index.html
> +        <input type="number" step="10" min="10" max="40" value="10">
Размер шрифта, увы, не меняется таким образом :(

2018-10-29 08:20 UTC, mokhov commented
<img width="343" alt="delorean dmc-12 2018-10-29 13-20-10" src="https://user-images.githubusercontent.com/357689/47637405-62d01880-db7d-11e8-84c0-59b5ec179be4.png">

Под плохо я имею ввиду вот такое

2018-12-15 08:20 UTC, closed without merging