Пакулин Сергей
urfu-2018/markup-task-3 pull request #91
Opened 2018-10-23 11:11 UTC by IIaKyJIuH

2018-10-23 11:11 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-23 11:45 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-26 19:44 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 08:25 UTC, mokhov requested changes
Не очень понятно зачем нужны таблицы, можно без них
🍅

2018-10-29 08:25 UTC, mokhov commented on index.css
> +    background-repeat: no-repeat;
Можно объединить в свойстве `background`

2018-10-29 17:15 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 17:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-13 12:54 UTC, mokhov commented
Справа не красивый отступ, из-за этого появляется горизонтальный скролл 🍅

2018-11-14 05:23 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-11-14 05:28 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-12-15 08:21 UTC, closed without merging