simple paper
urfu-2018/markup-task-3 pull request #94
Opened 2018-10-23 11:20 UTC by MaxtiCorn

2018-10-23 11:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-29 08:28 UTC, mokhov commented
<img width="86" alt="delorean dmc-12 2018-10-29 13-27-34" src="https://user-images.githubusercontent.com/357689/47637726-72039600-db7e-11e8-9ade-ce99cb936c1a.png">

Буква первая наползает на текст

2018-10-29 08:28 UTC, mokhov requested changes
🍅

2018-10-29 08:28 UTC, mokhov commented on index.html
> +                    Sunday, October 23, 2018
Для дат можно использовать другой тег

2018-10-29 08:28 UTC, mokhov commented on index.html
> +                    <img src="https://clck.ru/Eaipk"
Содержимое атрибута `alt` должно отвечать на вопрос «Что изображено на картинке?»

2018-10-30 09:11 UTC, honest-hrundel commented
:tomato: Не пройден линтинг или базовые тесты

2018-10-30 09:14 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-10-31 06:41 UTC, MaxtiCorn commented
🍏

2018-11-13 12:51 UTC, closed without merging